/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.50
 * Generated at: 2017-08-31 19:32:09 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.medico;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import data.facades.PatientFacade;
import java.util.List;
import data.entities.Patient;
import data.facades.DoctorFacade;
import data.entities.Doctor;
import javax.naming.InitialContext;

public final class pacientes_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/medico/navigation.jsp", Long.valueOf(1504173988000L));
    _jspx_dependants.put("/medico/../message.jsp", Long.valueOf(1504173988000L));
    _jspx_dependants.put("/medico/../head.jsp", Long.valueOf(1504175693000L));
    _jspx_dependants.put("/medico/../footer.jsp", Long.valueOf(1504173988000L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<html>\n");
      out.write("    ");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<head>\n");
      out.write("    <title>ChronoMed</title>\n");
      out.write("    <link rel=\"icon\" href=\"favicon.ico\">\n");
      out.write("    <meta charset=\"utf-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("\n");
      out.write("    <link href=\"http://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.3.0/css/font-awesome.min.css\" rel=\"stylesheet\" type=\"text/css\">\n");
      out.write("\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css\">\n");
      out.write("    <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.min.js\"></script>\n");
      out.write("    <script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js\"></script>\n");
      out.write("\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/index.css\"> <!--RUTA ABSOLUTA AL CSS -->\n");
      out.write("    <!-- Form toggle slider -->\n");
      out.write("    <link href=\"https://gitcdn.github.io/bootstrap-toggle/2.2.2/css/bootstrap-toggle.min.css\" rel=\"stylesheet\">\n");
      out.write("    <script src=\"https://gitcdn.github.io/bootstrap-toggle/2.2.2/js/bootstrap-toggle.min.js\"></script>\n");
      out.write("\n");
      out.write("    <style>\n");
      out.write("\n");
      out.write("        .affix {\n");
      out.write("            top:0;\n");
      out.write("            width: 100%;\n");
      out.write("            z-index: 9999 !important;\n");
      out.write("            margin-top: 0px !important;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        \n");
      out.write("    </style>\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("        \n");
      out.write("    <body class=\"body-background\">\n");
      out.write("\n");
      out.write("        <div class=\"container\">\n");
      out.write("            <div class=\"row\">\n");
      out.write("                ");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
 DoctorFacade doctorFacade = InitialContext.doLookup("java:global/ChronoMed/DoctorFacade");
    Doctor doctor = (Doctor) request.getSession().getAttribute("user");
      out.write("\n");
      out.write("<div class=\"section\">\n");
      out.write("    <div class=\"container logo-header\">\n");
      out.write("        <div class=\"row\">\n");
      out.write("            <div class=\"col-md-3\">\n");
      out.write("                <img src=\"/ChronoMed/images/ChronoMed.png\" class=\"img-responsive\">\n");
      out.write("            </div>\n");
      out.write("            <div class=\"col-md-9\" id=\"print2\">\n");
      out.write("                <div class=\"text-right\">\n");
      out.write("                    <h1>Saludos,\n");
      out.write("                        Dr");
 if (doctor.getGender().equals("Femenino")) {
                                out.print("a");
                            }
      out.write(". <span class=\"label label-primary\">");
      out.print( doctor.getSurname());
      out.write("</span>\n");
      out.write("                    </h1>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<div class=\"col-md-3\" id=\"print1\">\n");
      out.write("    <div class=\"list-group\">\n");
      out.write("        <a class=\"list-group-item\n");
      out.write("           ");
 if (request.getRequestURI().contains("pacientes")) { 
      out.write(" active");
 }
      out.write("\"\n");
      out.write("           href=\"/ChronoMed/medico/pacientes.jsp\">Mis pacientes</a>\n");
      out.write("        <a class=\"list-group-item\n");
      out.write("           ");
 if (request.getRequestURI().contains("datos")) { 
      out.write(" active");
 }
      out.write("\"\n");
      out.write("           href=\"/ChronoMed/medico/datos.jsp\">Mis datos</a>\n");
      out.write("    </div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("                ");

                    List<Patient> nifPatientList = (List<Patient>) request.getAttribute("patients");
                    List<Patient> healthCardPatientList = (List<Patient>) request.getAttribute("healthcardPatients");
                
      out.write("\n");
      out.write("                <div class=\"col-md-9\">\n");
      out.write("                    <div class=\"signin-form-container\">\n");
      out.write("                        <div class=\"row\">\n");
      out.write("                            <div class=\"col-md-6\">\n");
      out.write("                                <form class=\"form-horizontal\" method=\"GET\" role=\"form\" action=\"/ChronoMed/FrontController\">\n");
      out.write("                                    <input type=\"hidden\" value=\"SearchMyPatientsByHealthcardCommand\" name=\"command\">\n");
      out.write("                                    <div class=\"input-group input-group-lg\">\n");
      out.write("                                        <input type=\"text\" class=\"form-control\" placeholder=\"Buscar por tarjeta...\" name=\"searchHealthCardNumber\">\n");
      out.write("                                        <span class=\"input-group-addon\" id=\"basic-addon2\">\n");
      out.write("                                            <button class=\"btn-link\" type=\"submit\"><i class=\"fa  -circle fa-search\"></i></button>\n");
      out.write("                                        </span>\n");
      out.write("                                    </div>\n");
      out.write("                                </form>\n");
      out.write("                            </div>\n");
      out.write("\n");
      out.write("                            <div class=\"col-md-6\">\n");
      out.write("                                <form class=\"form-horizontal\" method=\"GET\" role=\"form\" action=\"/ChronoMed/FrontController\">\n");
      out.write("                                    <input type=\"hidden\" value=\"SearchMyPatientsByNifCommand\" name=\"command\">\n");
      out.write("                                    <div class=\"input-group input-group-lg\">\n");
      out.write("                                        <input type=\"text\" class=\"form-control\" placeholder=\"Buscar por DNI...\" name=\"searchNif\">\n");
      out.write("                                        <span class=\"input-group-addon\" id=\"basic-addon2\">\n");
      out.write("                                            <button class=\"btn-link\" type=\"submit\"><i class=\"fa  -circle fa-search\"></i></button>\n");
      out.write("                                        </span>\n");
      out.write("                                    </div>\n");
      out.write("                                </form>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("\n");
      out.write("                        <div class=\"list-group\">\n");
      out.write("                            ");
 if (nifPatientList == null && healthCardPatientList == null) {
      out.write("\n");
      out.write("                            <h2 style=\"text-align: center;\"><span class=\"label label-default\"><i class=\"fa fa-info-circle\"></i> Introduzca su DNI o tarjeta sanitaria</span></h2>\n");
      out.write("                            ");

                            } else if (nifPatientList != null && !nifPatientList.isEmpty()) {
                                for (Patient patient : nifPatientList) {
                            
      out.write("\n");
      out.write("                            <a href=\"/ChronoMed/medico/vistapacienteshistorial.jsp?id=");
      out.print( patient.getId());
      out.write("\" class=\"list-group-item\">\n");
      out.write("                                <h4 class=\"list-group-item-heading\">");
      out.print( patient.getName());
      out.write(' ');
      out.print( patient.getSurname());
      out.write("<i class=\"-circle fa fa-2x  pull-right text-primary fa-angle-right\"></i></h4>\n");
      out.write("                                <p class=\"list-group-item-text\">\n");
      out.write("                                    ");
      out.print( patient.getNif());
      out.write("\n");
      out.write("                                </p>\n");
      out.write("                            </a>\n");
      out.write("                            ");

                                }
                            } else if (healthCardPatientList != null && !healthCardPatientList.isEmpty()) {
                                for (Patient patient : healthCardPatientList) {
                            
      out.write("\n");
      out.write("                            <a href=\"/ChronoMed/medico/vistapacienteshistorial.jsp?id=");
      out.print( patient.getId());
      out.write("\" class=\"list-group-item\">\n");
      out.write("                                <h4 class=\"list-group-item-heading\">");
      out.print( patient.getName());
      out.write(' ');
      out.print( patient.getSurname());
      out.write("<i class=\"-circle fa fa-2x  pull-right text-primary fa-angle-right\"></i></h4>\n");
      out.write("                                <p class=\"list-group-item-text\">\n");
      out.write("                                    ");
      out.print( patient.getNif());
      out.write("\n");
      out.write("                                </p>\n");
      out.write("                            </a>\n");
      out.write("\n");
      out.write("                            ");

                                }
                            } else {
                            
      out.write("\n");
      out.write("                            <h2 style=\"text-align: center;\"><span class=\"label label-default\"><i class=\"fa fa-exclamation-circle\"></i> No se ha encontrado ningún paciente</span></h2>\n");
      out.write("\n");
      out.write("                            ");

                                }
                            
      out.write("\n");
      out.write("\n");
      out.write("                        </div>\n");
      out.write("\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        ");
      out.write("<div class=\"section\"></div>\n");
String message = (String) request.getAttribute("message");
    if (message != null) {

      out.write("\n");
      out.write("<div class=\"modal fade\" id=\"myModal\" role=\"dialog\">\n");
      out.write("    <div class=\"modal-dialog\">\n");
      out.write("        <div class=\"modal-content\">\n");
      out.write("            <div class=\"modal-header\">\n");
      out.write("                <button type=\"button\" class=\"close\" data-dismiss=\"modal\">&times;</button>\n");
      out.write("                <h4 class=\"modal-title\"><i class=\"fa fa-info-circle\"></i> Información importante</h4>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"modal-body\">\n");
      out.write("                <p>");
      out.print(message);
      out.write("</p>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"modal-footer\">\n");
      out.write("                <button type=\"button\" class=\"btn btn-default\" data-dismiss=\"modal\">Cerrar</button>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("    </div>\n");
      out.write("</div>\n");
      out.write("<script> $(\"#myModal\").modal(\"show\")</script>\n");
}
      out.write("\n");
      out.write("\n");
      out.write("<div class=\"bottom-navbar navbar navbar-default navbar-fixed-bottom navbar-inverse\">\n");
      out.write("    <div class=\"container\">\n");
      out.write("        <div class=\"navbar-header\">\n");
      out.write("            <button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\" data-target=\"#navbar-ex-collapse\">\n");
      out.write("                <span class=\"sr-only\">Toggle navigation</span>\n");
      out.write("                <span class=\"icon-bar\"></span>\n");
      out.write("                <span class=\"icon-bar\"></span>\n");
      out.write("                <span class=\"icon-bar\"></span>\n");
      out.write("            </button>\n");
      out.write("            <a class=\"navbar-brand\" href=\"/ChronoMed/FrontController?command=LogOutCommand\"><i class=\"fa  fa-sign-out\"></i>Cerrar sesión</a>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"collapse navbar-collapse\" id=\"navbar-ex-collapse\">\n");
      out.write("            <ul class=\"nav navbar-nav navbar-right\">\n");
      out.write("                <li>\n");
      out.write("                    <a href=\"/ChronoMed/terminosycondiciones.jsp\">Términos y condiciones</a>\n");
      out.write("                </li>\n");
      out.write("                <li>\n");
      out.write("                    <a href=\"mailto:ayuda@chronomed.com\">Ayuda</a>\n");
      out.write("                </li>\n");
      out.write("                <li>\n");
      out.write("                    <a href=\"/ChronoMed/db.jsp\" target=\"_blank\">Base de datos</a>\n");
      out.write("                </li>\n");
      out.write("            </ul>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</div>");
      out.write("\n");
      out.write("\n");
      out.write("    </body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
