/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.50
 * Generated at: 2017-08-31 19:32:20 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.paciente;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.List;
import data.entities.Medicalhistory;
import data.facades.MedicalhistoryFacade;
import data.facades.PatientFacade;
import javax.naming.InitialContext;
import data.entities.Patient;

public final class historial_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/paciente/../footer.jsp", Long.valueOf(1504173988000L));
    _jspx_dependants.put("/paciente/../head.jsp", Long.valueOf(1504175693000L));
    _jspx_dependants.put("/paciente/navigation.jsp", Long.valueOf(1504173988000L));
    _jspx_dependants.put("/paciente/../message.jsp", Long.valueOf(1504173988000L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<html>\n");
      out.write("    ");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<head>\n");
      out.write("    <title>ChronoMed</title>\n");
      out.write("    <link rel=\"icon\" href=\"favicon.ico\">\n");
      out.write("    <meta charset=\"utf-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("\n");
      out.write("    <link href=\"http://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.3.0/css/font-awesome.min.css\" rel=\"stylesheet\" type=\"text/css\">\n");
      out.write("\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css\">\n");
      out.write("    <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.min.js\"></script>\n");
      out.write("    <script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js\"></script>\n");
      out.write("\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/index.css\"> <!--RUTA ABSOLUTA AL CSS -->\n");
      out.write("    <!-- Form toggle slider -->\n");
      out.write("    <link href=\"https://gitcdn.github.io/bootstrap-toggle/2.2.2/css/bootstrap-toggle.min.css\" rel=\"stylesheet\">\n");
      out.write("    <script src=\"https://gitcdn.github.io/bootstrap-toggle/2.2.2/js/bootstrap-toggle.min.js\"></script>\n");
      out.write("\n");
      out.write("    <style>\n");
      out.write("\n");
      out.write("        .affix {\n");
      out.write("            top:0;\n");
      out.write("            width: 100%;\n");
      out.write("            z-index: 9999 !important;\n");
      out.write("            margin-top: 0px !important;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        \n");
      out.write("    </style>\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("        \n");
      out.write("    <body class=\"body-background\">\n");
      out.write("\n");
      out.write("        <div class=\"container\">\n");
      out.write("            <div class=\"row\">\n");
      out.write("                ");
      out.write('\n');
      out.write('\n');
      out.write('\n');
 PatientFacade patientFacade = InitialContext.doLookup("java:global/ChronoMed/PatientFacade");
    Patient patient = (Patient) request.getSession().getAttribute("user");
      out.write("\n");
      out.write("<div class=\"section\">\n");
      out.write("    <div class=\"container logo-header\">\n");
      out.write("        <div class=\"row\">\n");
      out.write("            <div class=\"col-md-3\">\n");
      out.write("                <img src=\"/ChronoMed/images/ChronoMed.png\" class=\"img-responsive\">\n");
      out.write("            </div>\n");
      out.write("            <div class=\"col-md-9\">\n");
      out.write("                <div class=\"text-right\">\n");
      out.write("                    <h1>Saludos,\n");
      out.write("                        Sr");
 if (patient.getGender().equals("Femenino")) {
                                out.print("a");
                            }
      out.write(". <span class=\"label label-primary\">");
      out.print( patient.getSurname());
      out.write("</span>\n");
      out.write("                    </h1>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</div>\n");
      out.write("<div class=\"col-md-3\" id=\"print1\">\n");
      out.write("    <div class=\"list-group\">\n");
      out.write("        <a href=\"/ChronoMed/paciente/historial.jsp\" class=\"list-group-item\n");
      out.write("           ");
 if (request.getRequestURI().contains("historial")) { 
      out.write(" active");
 }
      out.write("\">\n");
      out.write("            Mi historial médico</a>\n");
      out.write("        <a href=\"/ChronoMed/paciente/citas.jsp\" class=\"list-group-item\n");
      out.write("           ");
 if (request.getRequestURI().contains("citas")) { 
      out.write(" active");
 }
      out.write("\">\n");
      out.write("            Mi historial de citas</a>\n");
      out.write("        <a href=\"/ChronoMed/paciente/medicos.jsp\" class=\"list-group-item\n");
      out.write("           ");
 if (request.getRequestURI().contains("medicos")) { 
      out.write(" active");
 }
      out.write("\">\n");
      out.write("            Mis médicos</a>    \n");
      out.write("        <a href=\"/ChronoMed/paciente/datos.jsp\" class=\"list-group-item\n");
      out.write("           ");
 if (request.getRequestURI().contains("datos")) { 
      out.write(" active");
 }
      out.write("\">\n");
      out.write("            Mis datos</a>\n");
      out.write("    </div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("                ");

                    MedicalhistoryFacade medicalhistoryFacade = InitialContext.doLookup("java:global/ChronoMed/MedicalhistoryFacade");
                    Medicalhistory medicalhistory = medicalhistoryFacade.findByPatient(patient).get(0);
                
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("                <div class=\"col-md-9\">\n");
      out.write("                    <div class=\"signin-form-container\">\n");
      out.write("                        <h1 class=\"text-primary text-center\"><small>Historial de</small><br>Sr");
 if (patient.getGender().equals("Femenino")) {
                                out.print("a");
                            }
      out.write('.');
      out.write(' ');
      out.print(patient.getName() + " " + patient.getSurname());
      out.write("</h1>\n");
      out.write("\n");
      out.write("                        <blockquote>\n");
      out.write("                            <footer>Grupo sanguíneo</footer>\n");
      out.write("                            <p>");
      out.print(medicalhistory.getBloodType());
      out.write("</p>\n");
      out.write("                        </blockquote>\n");
      out.write("                        <blockquote>\n");
      out.write("                            <footer>Enfermedades</footer>\n");
      out.write("                            <p>");
      out.print(medicalhistory.getPathologies());
      out.write("</p>\n");
      out.write("                        </blockquote>\n");
      out.write("                        <blockquote>\n");
      out.write("                            <footer>Operaciones</footer>\n");
      out.write("                            <p>");
      out.print(medicalhistory.getSurgeries());
      out.write("</p>\n");
      out.write("                        </blockquote>\n");
      out.write("\n");
      out.write("                        <blockquote>\n");
      out.write("                            <footer>Alergias</footer>\n");
      out.write("                            <p>");
      out.print(medicalhistory.getAllergies());
      out.write("</p>\n");
      out.write("                        </blockquote>\n");
      out.write("                        <blockquote>\n");
      out.write("                            <footer>Historial familiar</footer>\n");
      out.write("                            <p>");
      out.print(medicalhistory.getFamilyHistory());
      out.write("</p>\n");
      out.write("                        </blockquote>\n");
      out.write("                        <blockquote>\n");
      out.write("                            <footer>Otros</footer>\n");
      out.write("                            <p>");
      out.print(medicalhistory.getOthers());
      out.write("</p>\n");
      out.write("                        </blockquote>\n");
      out.write("                        <div class=\"row\">\n");
      out.write("                            <div class=\"col-md-12\" id=\"print3\">\n");
      out.write("                                <button class=\"btn btn-primary btn-block\" onclick=\"window.print()\">Exportar historial <i class=\"fa  fa-print\"></i>\n");
      out.write("                                </button><br>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        ");
      out.write("<div class=\"section\"></div>\n");
String message = (String) request.getAttribute("message");
    if (message != null) {

      out.write("\n");
      out.write("<div class=\"modal fade\" id=\"myModal\" role=\"dialog\">\n");
      out.write("    <div class=\"modal-dialog\">\n");
      out.write("        <div class=\"modal-content\">\n");
      out.write("            <div class=\"modal-header\">\n");
      out.write("                <button type=\"button\" class=\"close\" data-dismiss=\"modal\">&times;</button>\n");
      out.write("                <h4 class=\"modal-title\"><i class=\"fa fa-info-circle\"></i> Información importante</h4>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"modal-body\">\n");
      out.write("                <p>");
      out.print(message);
      out.write("</p>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"modal-footer\">\n");
      out.write("                <button type=\"button\" class=\"btn btn-default\" data-dismiss=\"modal\">Cerrar</button>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("    </div>\n");
      out.write("</div>\n");
      out.write("<script> $(\"#myModal\").modal(\"show\")</script>\n");
}
      out.write("\n");
      out.write("\n");
      out.write("<div class=\"bottom-navbar navbar navbar-default navbar-fixed-bottom navbar-inverse\">\n");
      out.write("    <div class=\"container\">\n");
      out.write("        <div class=\"navbar-header\">\n");
      out.write("            <button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\" data-target=\"#navbar-ex-collapse\">\n");
      out.write("                <span class=\"sr-only\">Toggle navigation</span>\n");
      out.write("                <span class=\"icon-bar\"></span>\n");
      out.write("                <span class=\"icon-bar\"></span>\n");
      out.write("                <span class=\"icon-bar\"></span>\n");
      out.write("            </button>\n");
      out.write("            <a class=\"navbar-brand\" href=\"/ChronoMed/FrontController?command=LogOutCommand\"><i class=\"fa  fa-sign-out\"></i>Cerrar sesión</a>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"collapse navbar-collapse\" id=\"navbar-ex-collapse\">\n");
      out.write("            <ul class=\"nav navbar-nav navbar-right\">\n");
      out.write("                <li>\n");
      out.write("                    <a href=\"/ChronoMed/terminosycondiciones.jsp\">Términos y condiciones</a>\n");
      out.write("                </li>\n");
      out.write("                <li>\n");
      out.write("                    <a href=\"mailto:ayuda@chronomed.com\">Ayuda</a>\n");
      out.write("                </li>\n");
      out.write("                <li>\n");
      out.write("                    <a href=\"/ChronoMed/db.jsp\" target=\"_blank\">Base de datos</a>\n");
      out.write("                </li>\n");
      out.write("            </ul>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</div>");
      out.write("\n");
      out.write("\n");
      out.write("    </body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
