/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.50
 * Generated at: 2017-08-31 10:34:54 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/head.jsp", Long.valueOf(1504175693000L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

 request.getSession().invalidate(); 
      out.write("\n");
      out.write("\n");
      out.write("<html>\n");
      out.write("    ");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<head>\n");
      out.write("    <title>ChronoMed</title>\n");
      out.write("    <link rel=\"icon\" href=\"favicon.ico\">\n");
      out.write("    <meta charset=\"utf-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("\n");
      out.write("    <link href=\"http://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.3.0/css/font-awesome.min.css\" rel=\"stylesheet\" type=\"text/css\">\n");
      out.write("\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css\">\n");
      out.write("    <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.min.js\"></script>\n");
      out.write("    <script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js\"></script>\n");
      out.write("\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/index.css\"> <!--RUTA ABSOLUTA AL CSS -->\n");
      out.write("    <!-- Form toggle slider -->\n");
      out.write("    <link href=\"https://gitcdn.github.io/bootstrap-toggle/2.2.2/css/bootstrap-toggle.min.css\" rel=\"stylesheet\">\n");
      out.write("    <script src=\"https://gitcdn.github.io/bootstrap-toggle/2.2.2/js/bootstrap-toggle.min.js\"></script>\n");
      out.write("\n");
      out.write("    <style>\n");
      out.write("\n");
      out.write("        .affix {\n");
      out.write("            top:0;\n");
      out.write("            width: 100%;\n");
      out.write("            z-index: 9999 !important;\n");
      out.write("            margin-top: 0px !important;\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        \n");
      out.write("    </style>\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("\n");
      out.write("    <body>\n");
      out.write("        <div class=\"cover\" id=\"intro-section\">\n");
      out.write("            <div class=\"background-image-fixed cover-image\" style=\"background-image : url('images/medicamentos.jpeg')\"></div>\n");
      out.write("            <div class=\"container\">\n");
      out.write("                <div class=\"row form\">\n");
      out.write("                    <div class=\"col-md-5 logo\">\n");
      out.write("                        <img src=\"images/ChronoMed.png\" class=\"center-block img-responsive logo\">\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"col-md-7 signin-form\">\n");
      out.write("                        <ul class=\"nav nav-justified nav-tabs\">\n");
      out.write("\n");
      out.write("                            <li class=\"active\">\n");
      out.write("                                <a href=\"#\"><i class=\"fa  fa-lg fa-user\"></i>Inicio de sesión<br></a>\n");
      out.write("                            </li>\n");
      out.write("                            <li>\n");
      out.write("                            </li>\n");
      out.write("                            <li>                                \n");
      out.write("                            </li>\n");
      out.write("                            <li>                                \n");
      out.write("                            </li>\n");
      out.write("                        </ul>\n");
      out.write("                        <form action=\"FrontController\" method=\"POST\" class=\"form-horizontal text-right signin-form-container\" role=\"form\">\n");
      out.write("                            <input type=\"hidden\" value=\"LoginCommand\" name=\"command\">\n");
      out.write("                            <div class=\"container\">\n");
      out.write("                                <div class=\"row\">\n");
      out.write("                                    ");
String error = (String) request.getAttribute("error");
                                        if (error != null) {
                                    
      out.write("\n");
      out.write("                                    <div class=\"col-md-12 alert alert-danger\" style=\"text-align: center\">\n");
      out.write("                                        ");
      out.print( error);
      out.write("\n");
      out.write("                                    </div>\n");
      out.write("                                    ");
}
      out.write("\n");
      out.write("                                    <div class=\"col-md-8\">\n");
      out.write("                                        <div class=\"form-group has-feedback\">\n");
      out.write("                                            <div class=\"input-group\">\n");
      out.write("                                                <span class=\"input-group-addon\" id=\"basic-addon1\"><i class=\"fa fa-envelope\"></i></span>\n");
      out.write("                                                <input type=\"email\" class=\"form-control\" name=\"email\" id=\"inputEmail\" placeholder=\"Email\">\n");
      out.write("                                            </div>\n");
      out.write("                                        </div>\n");
      out.write("                                        <div class=\"form-group has-feedback\">\n");
      out.write("                                            <div class=\"input-group\">\n");
      out.write("                                                <span class=\"input-group-addon\" id=\"basic-addon1\"><i class=\"fa fa-key\"></i></span>\n");
      out.write("                                                <input type=\"password\" class=\"form-control\" name=\"password\" id=\"inputPassword\" placeholder=\"Contraseña\">\n");
      out.write("                                            </div>\n");
      out.write("                                        </div>\n");
      out.write("                                    </div>\n");
      out.write("\n");
      out.write("                                    <div class=\"col-md-4\">\n");
      out.write("                                        <div class=\"form-group\">\n");
      out.write("                                            <button type=\"submit\" class=\"btn btn-lg btn-primary\">\n");
      out.write("                                                <i class=\"fa fa-2x fa-sign-in\"></i><br>Entrar\n");
      out.write("                                            </button>\n");
      out.write("                                        </div>\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                        </form>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"navbar navbar-inverse\" id=\"nav\" style=\"margin-top:-50px;\">\n");
      out.write("            <div class=\"container\">\n");
      out.write("                <div class=\"navbar-header\">\n");
      out.write("                    <button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\" data-target=\"#navbar-ex-collapse\">\n");
      out.write("                        <span class=\"sr-only\">Toggle navigation</span>\n");
      out.write("                        <span class=\"icon-bar\"></span>\n");
      out.write("                        <span class=\"icon-bar\"></span>\n");
      out.write("                        <span class=\"icon-bar\"></span>\n");
      out.write("                    </button>\n");
      out.write("                    <a class=\"navbar-brand\" href=\"#\">© ChronoMed 2017</a>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"collapse navbar-collapse\" id=\"navbar-ex-collapse\">\n");
      out.write("                    <ul class=\"nav navbar-nav navbar-right\">\n");
      out.write("                        <li>\n");
      out.write("                            <a href=\"#intro-section\">Inicio</a>\n");
      out.write("                        </li>\n");
      out.write("                        <li class=\"\">\n");
      out.write("                            <a href=\"#services-section\">Servicios<br></a>\n");
      out.write("                        </li>\n");
      out.write("                        <li class=\"\">\n");
      out.write("                            <a href=\"#team-section\">Equipo<br></a>\n");
      out.write("                        </li>\n");
      out.write("                        <li>\n");
      out.write("                            <a href=\"#contact-section\">Contacto<br></a>\n");
      out.write("                        </li>\n");
      out.write("                    </ul>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"section\" id=\"services-section\">\n");
      out.write("            <div class=\"container\">\n");
      out.write("                <div class=\"row\">\n");
      out.write("                    <div class=\"col-md-12\">\n");
      out.write("                        <h1>¿Qué me puede ofrecer ChronoMed?</h1>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"section section-primary services-section\">\n");
      out.write("            <div class=\"container\">\n");
      out.write("                <div class=\"row\">\n");
      out.write("                    <div class=\"col-md-4 text-center\">\n");
      out.write("                        <img src=\"images/paciente.jpeg\" class=\"center-block img-responsive\">\n");
      out.write("                        <h2 class=\"text-center\">Como paciente</h2>\n");
      out.write("                        <p>Una manera rápida de acceder a tu historial médico desde casa, tu trabajo\n");
      out.write("                            o donde sea. Te ahorrarás la necesidad de tener un historial en cada centro\n");
      out.write("                            médico que visites. También te avisaremos cuando algún médico visite\n");
      out.write("                            tu historial. Tu privacidad y la seguridad de tus datos médicos están en\n");
      out.write("                            buenas manos.</p>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"col-md-4\">\n");
      out.write("                        <img src=\"images/medico.jpg\" class=\"center-block img-responsive\">\n");
      out.write("                        <h2 class=\"text-center\">Como médico</h2>\n");
      out.write("                        <p class=\"text-center\">Un portal único para acceder al historial de todos tus pacientes. Podrás\n");
      out.write("                            añadir o consultar información como enfermedades actuales, distintas consultas\n");
      out.write("                            que el paciente ha tenido, etc. Deja atrás esas peticiones a pacientes\n");
      out.write("                            para que traigan su historial médico. ¡Sigue ejerciendo tu profesión de\n");
      out.write("                            manera más eficaz!</p>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"col-md-4 text-center\">\n");
      out.write("                        <img src=\"images/administrativo.jpg\" class=\"center-block img-responsive\">\n");
      out.write("                        <h2 class=\"text-center\">Como administrativo</h2>\n");
      out.write("                        <p>Un sistema eficaz y fiable para la asignación de pacientes a médicos.\n");
      out.write("                            Evitarás las largas colas que se forman con pacientes que buscan su historial\n");
      out.write("                            médico del centro concreto, ya que estos podrán acceder desde cualquier\n");
      out.write("                            lugar. Tu única tarea: que tanto pacientes como médicos comienzen a usar\n");
      out.write("                            ChronoMed.\n");
      out.write("                            <br>\n");
      out.write("                            <br>\n");
      out.write("                        </p>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"section\" id=\"team-section\">\n");
      out.write("            <div class=\"container\">\n");
      out.write("                <div class=\"row\">\n");
      out.write("                    <div class=\"col-md-12\">\n");
      out.write("                        <h1 class=\"text-left\">Equipo</h1>\n");
      out.write("                        <p class=\"lead text-left\">Entre todos hacemos ChronoMed posible</p>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"row team-row\">\n");
      out.write("                    <div class=\"col-sm-2\">\n");
      out.write("                        <img src=\"images/team/al.jpg\" class=\"img-circle img-responsive\">\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"col-sm-4\">\n");
      out.write("                        <h3 class=\"text-left\">Adrián Louro</h3>\n");
      out.write("                        <p class=\"lead text-left\">Desarrollador</p>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"col-sm-2\">\n");
      out.write("                        <img class=\"img-circle img-responsive\" src=\"images/team/gm.jpeg\">\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"col-sm-4\">\n");
      out.write("                        <h3 class=\"text-left font-bold\">Gerardo Medina</h3>\n");
      out.write("                        <p class=\"lead text-left\">Desarrollador</p>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"row team-row\">\n");
      out.write("                    <div class=\"col-sm-2\">\n");
      out.write("                        <img src=\"images/team/ss.jpg\" class=\"img-circle img-responsive\">\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"col-sm-4\">\n");
      out.write("                        <h3 class=\"text-left\">Saskia Santana</h3>\n");
      out.write("                        <p class=\"lead text-left\">Desarrollador</p>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"col-sm-2\">\n");
      out.write("                        <img src=\"images/team/og.jpg\" class=\"img-circle img-responsive\">\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"col-sm-4 text-center\">\n");
      out.write("                        <h3 class=\"text-left\">Óscar García</h3>\n");
      out.write("                        <p class=\"lead text-left\">Desarrollador</p>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"row team-row\">\n");
      out.write("                    <div class=\"col-sm-2\">\n");
      out.write("                        <img src=\"images/team/jd.png\" class=\"img-circle img-responsive\">\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"col-sm-4\">\n");
      out.write("                        <h3 class=\"text-left\">Joel Delgado</h3>\n");
      out.write("                        <p class=\"lead text-left\">Desarrollador</p>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"col-sm-2\">\n");
      out.write("                        <img src=\"images/team/gc.jpg\" class=\"img-circle img-responsive\">\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"col-sm-4 text-center\">\n");
      out.write("                        <h3 class=\"text-left\">Guillermo Cubero</h3>\n");
      out.write("                        <p class=\"lead text-left\">Desarrollador</p>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"section section-primary\" id=\"contact-section\">\n");
      out.write("            <div class=\"container\">\n");
      out.write("                <div class=\"row\">\n");
      out.write("                    <div class=\"col-md-6 text-left\">\n");
      out.write("                        <h1>Contáctanos</h1>\n");
      out.write("                        <p>Escuela de Ingeniería Informática\n");
      out.write("                            <br>Campus de Tafira\n");
      out.write("                            <br>Universidad de Las Palmas de Gran Canaria\n");
      out.write("                            <br>Las Palmas, España</p>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"col-md-6\">\n");
      out.write("                        <iframe src=\"https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3520.4013483806557!2d-15.453591885445855!3d28.07329808264172!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0xc40942fde2813a9%3A0x8b61a40c00405a46!2sUniversidad+de+Las+Palmas+de+Gran+Canaria%3A+Escuela+de+Ingenier%C3%ADa+Inform%C3%A1tica!5e0!3m2!1sde!2ses!4v1487770546552\" width=\"600\" height=\"450\" frameborder=\"0\" style=\"border:0\" allowfullscreen=\"\" class=\"img-responsive\"></iframe>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"contact-section section\">\n");
      out.write("            <div class=\"container\">\n");
      out.write("                <div class=\"row text-center\">\n");
      out.write("                    <div class=\"col-xs-3 text-center\">\n");
      out.write("                        <a><i class=\"fa fa-5x  fa-instagram\"></i></a>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"col-xs-3\">\n");
      out.write("                        <a><i class=\"fa fa-5x  fa-twitter\"></i></a>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"col-xs-3\">\n");
      out.write("                        <a><i class=\"fa fa-5x  fa-facebook\"></i></a>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"col-xs-3 text-center\">\n");
      out.write("                        <a><i class=\"fa fa-5x  fa-github\"></i></a>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <script>\n");
      out.write("            $('#nav').affix({\n");
      out.write("                offset: {\n");
      out.write("                    top: $('#intro-section').height() - 50\n");
      out.write("                }\n");
      out.write("            });\n");
      out.write("\n");
      out.write("            $('body').scrollspy({target: \".navbar\", offset: 50});\n");
      out.write("\n");
      out.write("            $(\"#nav a\").on('click', function (event) {\n");
      out.write("                if (this.hash !== \"\") {\n");
      out.write("\n");
      out.write("                    event.preventDefault();\n");
      out.write("                    var hash = this.hash;\n");
      out.write("                    $('html, body').animate({\n");
      out.write("                        scrollTop: $(hash).offset().top\n");
      out.write("                    }, 800, function () {\n");
      out.write("\n");
      out.write("                        window.location.hash = hash;\n");
      out.write("                    });\n");
      out.write("\n");
      out.write("                }\n");
      out.write("\n");
      out.write("            });\n");
      out.write("        </script>\n");
      out.write("    </body></html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
